Add queries to GET /api/reviews endpoint
stormytuna/be-nc-games pull request #10
Opened 2022-12-13 16:19 UTC by stormytuna

2022-12-14 11:56 UTC, MRombi requested changes
Good work on this ticket Jack, we are almost there. Please, add the test I mentioned and implement the solution to pass them and then resubmit 🙂

2022-12-14 11:56 UTC, MRombi commented on __tests__/app.test.js
> +					if (pre && cur) {
We are not doing anything with the output of reduce, and pre and cur here are two objects so we could remove the reduce 🙂

2022-12-14 11:56 UTC, MRombi commented on __tests__/app.test.js
> +	});
We should add a test for the following:
- status 400 an invalid sort_by and order i.e. sort_by=banana
- status 200 a valid category with no reviews i.e. category=children's games (res is an empty array)
- status 404 if category does not exist i.e. category=banana

2022-12-15 10:14 UTC, Jodiech commented on models/models.reviews.js
> +const validOrders = ["asc", "desc"];
This needs to be moved out of the global and into the function, as you don't want to use it anywhere else.

2022-12-15 10:17 UTC, Jodiech commented on models/models.reviews.js
> +	// Conditionally adds filter
Please remove any comments :)

2022-12-15 10:26 UTC, merged